### ISSUE TITLE
ImGuiSelectableFlags_PressedOnClick becomes ImGuiSelectableFlags_SelectOnClick ?

### ISSUE THREAD

**Issue by DaveInDev** [gallickgunner/ImGui-Addons#14]
Hi there,
first, a big thx for this addon to Imgui.
Then it seems that there has been a litle change in Imgui, so that your file does not compile anymore with Imgui 1.77.
In imgui_internal.h it seems that ImGuiSelectableFlags_PressedOnClick becomes ImGuiSelectableFlags_SelectOnClick .
So you have to change accordingly you ImguiFileBrowser.ccp , line 615 .
I suppose that this line was in relation with the file filter combobox that seems to work ok.

**Comment by gallickgunner** [comment]
I'm glad you liked it. 1.77 might be WIP I guess, since the latest official release is 1.76. I've updated it till 1.75 btw. I won't be updating it with WIP versions since it's prone to modifications much more quickly than the official releases which come out in a while. 

Will check if this is the same scenario with 1.76, if so will update shortly. Thanks for mentioning that.

**Comment by DaveInDev** [comment]
oh ok. I'm new to Imgui, so I did not notice this "WIP" thing (I do not even know this acronym, I'm french). Anyway, thx again. Can I ask you with what backend do you use Imgui ? Because I'm using it with SDL2 and everything is not clear for me yet.

**Comment by gallickgunner** [comment]
No worries bro :) WIP means "Work In Progress" so it's like a beta version. I use the OpenGL-3 and GLFW backend. If you just want to use the addon and don't really have a specific ImGui version in mind, you can just clone this repo recursively and you'll get the latest ImGui version that is compatible with the addon.
