### ISSUE TITLE
validateFile extension bug

### ISSUE THREAD

**Issue by d3cod3** [gallickgunner/ImGui-Addons#15]
Hi, i've found a small bug inside the bool validateFile() function, file ImGuiFileBrowser.cpp, line 1055:

```c
std::string file_ext = idx == std::string::npos ? "" : selected_fn.substr(idx, selected_fn.length() - idx);
```
is returning ".ext"

while in needed the extension without the dot to correctly check, "ext"

so **idx+1**, in the substring extraction, fix the issue:

```c
std::string file_ext = idx == std::string::npos ? "" : selected_fn.substr(idx+1, selected_fn.length() - idx);
```

**Comment by gallickgunner** [comment]
Sorry, I didn't understand the last part. First of all, `valid_exts` contains the list of extensions that have the `.` preceding in their names. So when running `std::find` on that array we need to provide `.png` instead of just `png` to match an element from that array which is what the code does. Is that it or am I missing something?

Secondly a more technichal issue is that after the revamp the `Open` file dialog mode now only shows files that have the same extension as selected in the dropbox. So there is no need for validating any file since it already shows only files that are supported. I think I'll remove it after verifying there really isn't any connections to it.

**Comment by d3cod3** [comment]
You're right, sorry, my mistake, i was passing the extensions to the showFileDialog() method without the dots:

```c
showFileDialog("Select image", imgui_addons::ImGuiFileBrowser::DialogMode::OPEN, ImVec2(700,380), "jpg,jpeg,gif,png,tif,tiff")
```

so i was having the ```valid_exts``` populated with extensions without dots, and so the issue.

But maybe it could be good to add some sort of sanitize in the ```void ImGuiFileBrowser::setValidExtTypes(const std::string& valid_types_string)``` method, to eventually limit those kind of situations, like adding the dot if missing:

```c
if(extension.find('.') != std::string::npos) extension = "."+extension;
```
a trivial one, for example.

Thanks for your great imgui addon!
