### ISSUE TITLE
Is there a way to only display a browser for a single directory?

### ISSUE THREAD

**Issue by quou** [gallickgunner/ImGui-Addons#22]
I'm working on a game engine, and I'm already using this file browser to open and save projects and scenes. However, I'd also like to use it for selecting sprites, scripts, etc, but they are only in the Assets folder, so how could I modify it to only search in the Assets folder?

**Comment by gallickgunner** [comment]
Hmm, there is no such feature implemented currently. I guess you just want it for ease of use so everytime you try to open the dialog it opens in the assets folder? If so, do note that every instance of the filebrowser saves the last location. So you can, for example, have a separate button for opening sprites/scripts and assign a separate instance of the filebrowser with that button. Then you'll have to browse to the assets folder only once and it'll remember that on subsequent visits. Although this behavior is per runtime so it's not gonna be very useful if you are constantly closing then re-starting the whole application. I agree though, that this is a tedious thing that can be easily solved by providing an argument for a default path.

If you want to limit searching functionality, you can always just open the specific folder and start searching in it? If, however, you have the idea that we should strictly **_limit_** browsing in a single directory, I don't see any usecase for it. Do elaborate on that.

**Comment by quou** [comment]
Well, I would prefer if it would limit browsing to only the Assets folder and its subfolders, since the editor crashes if it tries to open a file outside of the Assets folder.

**Comment by gallickgunner** [comment]
Is that crashing related to the filebrowser or your engine? If it's related to your engine then I think this is just specific to your usecase so it's not gonna benefit the general populace. You should try to fix the crashing on your end.

If it's related to the filebrowser, then I'll need details on what causes crashing.

**Comment by quou** [comment]
Crashing is on my end, and something that was intentional, so as not to confuse files.

**Comment by gallickgunner** [comment]
> Crashing is on my end, and something that was intentional, so as not to confuse files.

Hmm, then I think this should be handled on your end. Since crashing shouldn't be the usual way to avoid things. Besides, the filebrowser is intended for navigation. So I see no point to limit it. What we can do and what has been implemented is to restrict the type of files that can be opened.  However, I understand there are various specific use cases where the general file browser won't fit and you'll have to do changes on your own. 

So I can't make this a feature for the general filebrowser but just listing some pointers on how _you_ can get the behaviour you want.

So there are 2 ways to navigate. Either by clicking the folders in the view box or through the top navi bar. First you'll want to pass an additional parameter ( the default path to asset folder) and [initialize](https://github.com/gallickgunner/ImGui-Addons/blob/f463e293d02fa8dbb972a94a2195fe923ab3b230/FileBrowser/ImGuiFileBrowser.cpp#L54)`current_path` with it. And create an additional enum say `LIMIT` to specify this new mode.

Next, we want to eliminate all folders so we can't navigate. The necessary line to modify is [here](https://github.com/gallickgunner/ImGui-Addons/blob/f463e293d02fa8dbb972a94a2195fe923ab3b230/FileBrowser/ImGuiFileBrowser.cpp#L825). Just add a check to avoid pushing into `subdirs`. That way you'll only have files listed in the view box.

Now for the navi bar, you can just check `mode == LIMIT` then return true at the [start](https://github.com/gallickgunner/ImGui-Addons/blob/f463e293d02fa8dbb972a94a2195fe923ab3b230/FileBrowser/ImGuiFileBrowser.cpp#L671). So nothing happens.

I believe that's all you'll need to do in order to get it going.

**Comment by quou** [comment]
Thanks for your help, I appreciate it.
