### ISSUE TITLE
Automatic "All supported extensions" option

### ISSUE THREAD

**Issue by Gargaj** [gallickgunner/ImGui-Addons#26]
Have an option on top of the extension filter combobox that filters through ALL supported file types (this is common with most software)

![image](https://user-images.githubusercontent.com/1702533/107227197-65d43780-6a1b-11eb-8651-9e809386461d.png)

**Comment by gallickgunner** [comment]
Good suggestions, both of them. Wanna submit a PR? xD This one's pretty simple and I think you'd already know how to do it. Instead of populating the vector with only extensions like `.txt .zip` etc you can use the vector as a map. Every odd index describing the extension like `Video Files` and every even index with a list of comma separated extensions like `*.mp4,*.mkv` etc. Then render both the text and the extension as in the above image. Will have to mess with the combobox size depending on the largest string combination. Atleast that's the way that came in my mind.

**Comment by Gargaj** [comment]
> Good suggestions, both of them. Wanna submit a PR? xD 

I'll take a look at some point.
