### ISSUE TITLE
Feature Request: Selecting folders

### ISSUE THREAD

**Issue by bwrsandman** [gallickgunner/ImGui-Addons#5]
I would like to be able to select a folder instead of a file.

**Comment by gallickgunner** [comment]
Hey, glad that the addon is of use to you. I'm sorry but I'm quite busy due to office work. The requested feature is very easy to add and you can do it yourself, trust me.

You just need to pass a bool to the `showOpenDialog` function to treat the folder as files too. Then at the end of the function just store the path to the folder if the "Open" button is clicked and if the bool variable passed is true. Currently the `name` is stored only if files are selected and `Open` is pressed. Also bypass the function calls to `validateFile()` as those are used to ensure the file extension is the same as selected in the dropdown. And you have it :)

**Comment by bwrsandman** [comment]
solved in #10
