### ISSUE TITLE
Incorrect child window height in "Invalid File!" popup

### ISSUE THREAD

**Issue by llunS** [gallickgunner/ImGui-Addons#52]
## Issue

- Invalid visual height with empty content
- User interaction is blocked, no OK button showing and thus no way back

See the screenshot below
<img width="358" alt="Screenshot 2023-06-03 at 06 16 48" src="https://github.com/gallickgunner/ImGui-Addons/assets/29365864/ce3c091f-8b1d-4005-8158-f2fbceb88726">

## Ways to reproduce

1. Open the dialog with only one extension provided (e.g. .zip)
2. Pick a nonexistent file path

## Cause

https://github.com/gallickgunner/ImGui-Addons/blob/380b617b10d62e8536722835b90b9ed67214420d/FileBrowser/ImGuiFileBrowser.cpp#L1007-L1008

The fact that `valid_exts.size() - 1` is regarded as "display extension count" is based on the assumption that there is a "All valid files" in the `valid_exts`, which is only true if users provided more than 1 extension.
In the case of 1 extension, `cw_height` would be 0 which is invalid for `BeginChild()`.

## Possible fix

- `auto ext_count = valid_exts.back() == "All valid files" ? valid_exts.size() - 1 : valid_exts.size()`, and replace the 2 occurrences of `valid_exts.size() - 1`

> P.S. I tried that and it works, except that the visual is not very pleasing with child window showing scrollbar, so I think it's best for the repo owner to fix this problem.

**Comment by gallickgunner** [comment]
Hi, nice find. I'm currently busy due to transitioning my workspace to linux so don't really have time to fix this. You can open up a PR maybe?

I think the scrollbar is appearing because of

`float cw_height = std::min<float>(4.0f * frame_height, cw_content_height);`

Currently it's being set to a maximum of `4 * frame_height`. In case of the number of extension being 4 or less, the child window height is being set the same as the content height. I think the scrollbars appear when the size of the content is the same or exceeds the window height. You could try adding a small factor to the window height to always make it bigger than the content incase the content has less than 4 extensions by doing

`float cw_height = std::min<float>(4.0f * frame_height, cw_content_height) + delta     // delta = a small amount like frame_height/2;`

If that doesn't work, you can always try passing the no scrollbar option to the `BeginChild` function when you have 4 or less extesnsions.

**Comment by llunS** [comment]
I will be opening up a PR this day or two, using your advice and tweak it a bit if it doesn't work.
Then we will see how it goes by the time the PR is open.

**Comment by llunS** [comment]
The PR is open.

And as a complete unrelated side note, consider removing the `SetNextWindowPos` and `SetNextWindowSize` in `showFileDialog()`, because in my use case with Multi-Viewport feature enabled in IMGUI, this will allow for the window size and position being persisted between dialog opening sessions and application sessions since it is persisted in `imgui.ini` instead of being fixed each time the dialog is open.

**Comment by gallickgunner** [comment]
Thanks for the PR. It's merged. I'll look into the function calls you mentioned when I get back to it. Happy coding.
