### ISSUE TITLE
Feature Request: Use history or current directory as default path on linux

### ISSUE THREAD

**Issue by bwrsandman** [gallickgunner/ImGui-Addons#6]
On Linux the file dialog will open only in the root folder.

**Comment by gallickgunner** [comment]
Ah, this is because the `DIR` structure in the ported `dirent.h` by Toni for windows already provides an entry that contains the absolute path. The standard header in linux however doesn't have it. You need to use `realpath()` I guess but this also has problems in cases of symbolic links as far as I gathered on the net.  

Since I don't have linux, I couldn't really test it and thus the feature is missing from the build. If you can try using `realpath` and submitting a PR that'd be really appreciated :) The only way I can help is tell you where to make the changes. 

1) First in the constructor, you'd have to initialize the current path with `./` as with the case of windows. You can just remove the defines here since now it's all the same.

2) Secondly, in the `readDIR()` function, line 543-548 are for getting absolute paths on Windows. Do the same for Linux using realpath, and that's it I guess.

**Comment by bwrsandman** [comment]
How about using `std::filesystem::current_path`?
It requires C++17 though

https://en.cppreference.com/w/cpp/filesystem/current_path

**Comment by bwrsandman** [comment]
Solved in #8
